/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/todos": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          task_name?: parameters["rowFilter.todos.task_name"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
          inserted_at?: parameters["rowFilter.todos.inserted_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["todos"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          task_name?: parameters["rowFilter.todos.task_name"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
          inserted_at?: parameters["rowFilter.todos.inserted_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          task_name?: parameters["rowFilter.todos.task_name"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
          inserted_at?: parameters["rowFilter.todos.inserted_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
        };
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  todos: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    task_name?: string;
    is_completed?: boolean;
    inserted_at: string;
    updated_at: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** todos */
  "body.todos": definitions["todos"];
  "rowFilter.todos.id": string;
  "rowFilter.todos.user_id": string;
  "rowFilter.todos.task_name": string;
  "rowFilter.todos.is_completed": string;
  "rowFilter.todos.inserted_at": string;
  "rowFilter.todos.updated_at": string;
}

export interface operations {}
